### ISSUE TITLE
Version 1.0 Tracking

### ISSUE THREAD

**Issue by srepollock** [srepollock/divine-engine#41]
Entity Component System Requirements

- [x] Unique game object ID’s for easy access
- [x] Entity-Component game object system
- [x] Game objects can send messages directly to the message system
- [x] Game objects can receive messages directly from the message system
- [x] Developers defined game objects loading from a project (outside of the game engine file system)
- [ ] Developer defined components loading from a project (outside of the game engine file system)
- [x] Game managers can access game objects for scene managing

Message System Requirements

- [ ] Stream-based messaging system
- [x] All objects can receive messages
- [x] All objects can receive messages of specific types
- [x] Objects do not receive messages they do not specify
- [x] Objects can unsubscribe from messages
- [x] Messages can send information from system to system

Render System Requirements

- [x] Scene loading
- [ ] Scene reloading
- [x] Rendering textures
- [x] Rendering sprite sheets
- [x] Rendering sprite animations from sprite sheets
- [x] Allows for layering of textures and UI objects
- [x] UI object selection

Physics System Requirements

- [x] Rigidbody components with force movement
- [x] Rigidbody object rotation
- [x] 2D box collider components with collision detection over the message system
- [x] 2D box collision response between game objects over the message system
- [x] Game world gravity effecting objects movement

Sound System Requirements

- [x] Can play game music
- [x] Can play sound effects
- [x] Can play music from game object call
- [x] Can change game music from manager objects
- [x] Can pause music
- [x] Can pause music from manager objects
- [x] Can play tracks on repeat
- [x] Can start music from the beginning at any time

Input System Requirements

- [x] Tracks keyboard input
- [x] Messages keyboard input to objects through the message system
- [ ] Objects can receive developer specified keyboard input
- [x] UI elements on press or action sends user input messages through the IO system to the message system for handling
- [ ] Controller input (Xbox controllers on Windows) handled by the IO system

Overall Engine Requirements

- [x] Insert new game objects while the game is running with incremental building
- [ ] Restart scene and insert new game objects with incremental building
- [x] Close and re-run application from the initial or specified scene and insert a new game object with the incremental building – specified by the project configuration
- [x] Specified scene loading on startup
- [ ] Unit tests for each system in the engine checking each function built into the engine for code debugging
- [x] Continuous integration testing running on source repository checking unit tests for passing to ensure no errors were added in the commit
- [x] Code linting run to ensure code requirements are met and running with tests
- [x] Engine error code system displaying and human readable to pinpoint errors
- [ ] Documentation covering 70%> of the code per stage delivered to ensure an API built with development
- [x] Reads an external project file system for developer objects
- [x] Deploy to npm on each push to master as a new version release
- [x] Runnable immediately after installation to a developer’s game project
- [ ] Builds an empty project from a console command for developers to get started
- [ ] Builds an example project from a console command for developers to see how the engine works
